// Generated by https://quicktype.io

export interface PokemonResponseTs {
    count:    number;
    next:     string;
    previous: null;
    results:  Response[];
}

export interface Response {
    name: string;
    url:  string;
}
